spring:
    application:
        name: regions
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: user
        password: user
    h2:
        console:
            enabled: true
            path: /h2-console
    sql:
        init:
            mode: always
springdoc:
  api-docs:
    path: /api-docs
logging:
  level:
    com: INFO
